.TH RAVENDARK-CLI "1" "June 2016" "ravendark-cli 0.12"
.SH NAME
ravendark-cli \- a remote procedure call client for RavenDark Core. 
.SH SYNOPSIS
ravendark-cli [options] <command> [params] \- Send command to RavenDark Core. 
.TP
ravendark-cli [options] help \- Asks RavenDark Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the ravendark-cli program. ravendark-cli is an RPC client used to send commands to RavenDark Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBravendarkd\fP, \fBravendark.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
